# Sample YAML file for TabbyAPI for Qwen3-30B-A3B 4.0bpw EXL3 on a pair of RTX 3090 (48GB total VRAM), where the GPU 1 also runs the monitors (so has less VRAM available):
# This requires the model to be previously downloaded to the specified folder

# Only relevant changes are set here.
# Exllamav3 is alpha software. This might have better speeds than llama.cpp, or be more viable to run than vLLM in some environments, 
# but may have (performance, stability, etc.) issues and some functionality (like separate reasoning_content, which ResearcParça has a workaround for) isn't available.

network:
  # ...
  port: 8086
  api_servers: ["OAI"]

model:
  model_dir: D:\tabbyAPI\models
  inline_model_loading: false
  use_dummy_models: false
  model_name: Qwen3-30B-A3B-exl3-4.0bpw
  max_seq_len: 262144
  tensor_parallel: false #not yet supported for this model in exllamav3
  gpu_split_auto: true
  autosplit_reserve: [0,2048]
  gpu_split: [24,21]
  cache_mode: 8,8   # For exllamav3, specify the pair k_bits,v_bits where k_bits and v_bits are integers from 2-8 (i.e. 8,8).
  vision: false

sampling:
  # Select a sampler override preset (default: None).
  # Find this in the sampler-overrides folder.
  # This overrides default fallbacks for sampler values that are passed to the API.
  # NOTE: safe_defaults is noob friendly and provides fallbacks for frontends that don't send sampling parameters.
  # Remove this for any advanced usage.
  override_preset: safe_defaults
